"""init

Revision ID: 5abb14baa932
Revises:
Create Date: 2026-09-01 00:00:00.000000

Squashed from the service's original two migrations (init + add parsed) --
geo had no production data yet, so this folds the schema straight to its
current shape (nullable location.name for address-proxy locations,
nullable+optional location.spot with the address-xor-spot CHECK
constraint) instead of layering more revisions on top.
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from geoalchemy2 import Geometry
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "5abb14baa932"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_geospatial_table(
        "country",
        sa.Column("id", sa.SmallInteger(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("code", sa.String(length=16), nullable=True),
        sa.Column(
            "spot",
            Geometry(
                geometry_type="POINT",
                srid=4326,
                dimension=2,
                spatial_index=False,
                from_text="ST_GeomFromEWKT",
                name="geometry",
            ),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_geospatial_index(
        "idx_country_spot",
        "country",
        ["spot"],
        unique=False,
        postgresql_using="gist",
        postgresql_ops={},
    )
    op.create_geospatial_table(
        "region",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("country_id", sa.SmallInteger(), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("code", sa.String(length=16), nullable=True),
        sa.Column(
            "spot",
            Geometry(
                geometry_type="POINT",
                srid=4326,
                dimension=2,
                spatial_index=False,
                from_text="ST_GeomFromEWKT",
                name="geometry",
            ),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["country_id"], ["country.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_geospatial_index(
        "idx_region_spot",
        "region",
        ["spot"],
        unique=False,
        postgresql_using="gist",
        postgresql_ops={},
    )
    op.create_geospatial_table(
        "city",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("region_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("acronym", sa.String(length=64), nullable=True),
        sa.Column(
            "spot",
            Geometry(
                geometry_type="POINT",
                srid=4326,
                dimension=2,
                spatial_index=False,
                from_text="ST_GeomFromEWKT",
                name="geometry",
            ),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["region_id"], ["region.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_geospatial_index(
        "idx_city_spot",
        "city",
        ["spot"],
        unique=False,
        postgresql_using="gist",
        postgresql_ops={},
    )
    op.create_geospatial_table(
        "address",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("city_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "name_tsv",
            postgresql.TSVECTOR(),
            sa.Computed("to_tsvector('simple', \"name\")", persisted=True),
            nullable=False,
        ),
        sa.Column("name", sa.String(length=512), nullable=False),
        sa.Column(
            "parsed", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column(
            "spot",
            Geometry(
                geometry_type="POINT",
                srid=4326,
                dimension=2,
                spatial_index=False,
                from_text="ST_GeomFromEWKT",
                name="geometry",
            ),
            nullable=True,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("edited_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["city_id"], ["city.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_geospatial_index(
        "idx_address_spot",
        "address",
        ["spot"],
        unique=False,
        postgresql_using="gist",
        postgresql_ops={},
    )
    op.create_index(
        "idx_spot_search_fts",
        "address",
        ["name_tsv"],
        unique=False,
        postgresql_using="gin",
    )
    op.create_index(
        "ix_spot_search_trgm",
        "address",
        ["name"],
        unique=False,
        postgresql_using="gin",
        postgresql_ops={"name": "gin_trgm_ops"},
    )
    op.create_geospatial_table(
        "location",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("address_id", sa.Uuid(), nullable=True),
        sa.Column("name", sa.String(length=512), nullable=True),
        sa.Column(
            "spot",
            Geometry(
                geometry_type="POINT",
                srid=4326,
                dimension=2,
                spatial_index=False,
                from_text="ST_GeomFromEWKT",
                name="geometry",
            ),
            nullable=True,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("edited_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["address_id"], ["address.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.CheckConstraint(
            "(address_id IS NOT NULL) != (spot IS NOT NULL)",
            name="ck_location_address_xor_spot",
        ),
    )
    op.create_geospatial_index(
        "idx_location_spot",
        "location",
        ["spot"],
        unique=False,
        postgresql_using="gist",
        postgresql_ops={},
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_geospatial_index(
        "idx_location_spot",
        table_name="location",
        postgresql_using="gist",
        column_name="spot",
    )
    op.drop_geospatial_table("location")
    op.drop_index(
        "ix_spot_search_trgm",
        table_name="address",
        postgresql_using="gin",
        postgresql_ops={"name": "gin_trgm_ops"},
    )
    op.drop_index(
        "idx_spot_search_fts", table_name="address", postgresql_using="gin"
    )
    op.drop_geospatial_index(
        "idx_address_spot",
        table_name="address",
        postgresql_using="gist",
        column_name="spot",
    )
    op.drop_geospatial_table("address")
    op.drop_geospatial_index(
        "idx_city_spot",
        table_name="city",
        postgresql_using="gist",
        column_name="spot",
    )
    op.drop_geospatial_table("city")
    op.drop_geospatial_index(
        "idx_region_spot",
        table_name="region",
        postgresql_using="gist",
        column_name="spot",
    )
    op.drop_geospatial_table("region")
    op.drop_geospatial_index(
        "idx_country_spot",
        table_name="country",
        postgresql_using="gist",
        column_name="spot",
    )
    op.drop_geospatial_table("country")
    # ### end Alembic commands ###
