"""address provenance and coverage cells

Revision ID: 5bae7df6dd2c
Revises: 88e6684f390c
Create Date: 2026-09-29 19:41:10.070624

Tags a bootstrap/re-sync-imported address with where it came from (``source``/
``source_id``) and when it was last confirmed to still exist upstream
(``synced_at``), so a re-sync run can tell its own rows apart from
manually-created ones (``source IS NULL``, never touched) before pruning
anything stale. ``address_coverage_cell`` tracks which fixed-size geographic
cells have already been fetched from an external source, so an on-demand
fetch outside any bulk-imported city can tell "never fetched" from "already
covered" without re-querying the source every time.
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5bae7df6dd2c"
down_revision: str | None = "88e6684f390c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "address_coverage_cell",
        sa.Column("cell_row", sa.Integer(), nullable=False),
        sa.Column("cell_col", sa.Integer(), nullable=False),
        sa.Column("source", sa.String(length=32), nullable=False),
        sa.Column("fetched_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "uq_address_coverage_cell",
        "address_coverage_cell",
        ["cell_row", "cell_col", "source"],
        unique=True,
    )
    op.add_column("address", sa.Column("source", sa.String(length=32), nullable=True))
    op.add_column(
        "address", sa.Column("source_id", sa.String(length=255), nullable=True)
    )
    op.add_column(
        "address", sa.Column("synced_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.create_index(
        "ix_address_source_sync",
        "address",
        ["source", "city_id", "synced_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_address_source_sync", table_name="address")
    op.drop_column("address", "synced_at")
    op.drop_column("address", "source_id")
    op.drop_column("address", "source")
    op.drop_index("uq_address_coverage_cell", table_name="address_coverage_cell")
    op.drop_table("address_coverage_cell")
    # ### end Alembic commands ###
