"""init

Revision ID: 60bac58e30bb
Revises:
Create Date: 2025-11-26 18:46:03.526563

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from profile.enum.contact import ContactType


# revision identifiers, used by Alembic.
revision: str = "60bac58e30bb"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

contact_type = sa.Enum(
    "email", "phone", "tg", "vk", "address", name="contact_type"
)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "diet",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("description", sa.String(length=512), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_diet_name"), "diet", ["name"], unique=False)

    op.create_table(
        "organization",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("type", sa.String(length=16), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )

    op.create_table(
        "person",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("surname", sa.String(length=128), nullable=False),
        sa.Column("patronymic", sa.String(length=128), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("edited_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )

    op.create_table(
        "student_degree",
        sa.Column("id", sa.SmallInteger(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=32), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )

    op.create_table(
        "contact",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("person_id", sa.Uuid(), nullable=False),
        sa.Column("type", contact_type, nullable=False),
        sa.Column("value", sa.String(length=256), nullable=False),
        sa.Column("is_main", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["person_id"], ["person.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )

    op.create_table(
        "profile",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("birthdate", sa.Date(), nullable=True),
        sa.Column("workplace_id", sa.Uuid(), nullable=True),
        sa.Column("diet_id", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("edited_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["diet_id"],
            ["diet.id"],
        ),
        sa.ForeignKeyConstraint(["id"], ["person.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["workplace_id"], ["organization.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
    )

    op.create_table(
        "student_group",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=32), nullable=False),
        sa.Column("degree_id", sa.SmallInteger(), nullable=False),
        sa.Column("faculty_id", sa.Uuid(), nullable=False),
        sa.Column("grade", sa.SmallInteger(), nullable=False),
        sa.ForeignKeyConstraint(
            ["degree_id"],
            ["student_degree.id"],
        ),
        sa.ForeignKeyConstraint(
            ["faculty_id"],
            ["organization.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_student_group_name"), "student_group", ["name"], unique=False
    )

    op.create_table(
        "passport",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("profile_id", sa.Uuid(), nullable=False),
        sa.Column("number", sa.String(length=32), nullable=False),
        sa.Column("expire_date", sa.Date(), nullable=False),
        sa.Column("is_foreign", sa.Boolean(), nullable=False),
        sa.Column("issued_date", sa.Date(), nullable=True),
        sa.Column("issued_authority", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("edited_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["profile_id"], ["profile.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )

    op.create_table(
        "student",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("student_id", sa.String(length=64), nullable=False),
        sa.Column("faculty_id", sa.Uuid(), nullable=True),
        sa.Column("group_id", sa.BigInteger(), nullable=False),
        sa.Column("is_budget", sa.Boolean(), nullable=True),
        sa.Column("is_full", sa.Boolean(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["faculty_id"], ["organization.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["group_id"],
            ["student_group.id"],
        ),
        sa.ForeignKeyConstraint(
            ["id"],
            ["profile.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_student_student_id"), "student", ["student_id"], unique=False
    )

    op.create_table(
        "name_variant",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("surname", sa.String(length=128), nullable=False),
        sa.Column("patronymic", sa.String(length=128), nullable=True),
        sa.ForeignKeyConstraint(["id"], ["passport.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("name_variant")
    op.drop_index(op.f("ix_student_student_id"), table_name="student")
    op.drop_table("student")
    op.drop_table("passport")
    op.drop_index(op.f("ix_student_group_name"), table_name="student_group")
    op.drop_table("student_group")
    op.drop_table("profile")
    op.drop_table("contact")
    op.drop_table("student_degree")
    op.drop_table("person")
    op.drop_index(op.f("ix_organization_name"), table_name="organization")
    op.drop_table("organization")
    op.drop_index(op.f("ix_diet_name"), table_name="diet")
    op.drop_table("diet")
    op.execute("DROP TYPE contact_type")
    # ### end Alembic commands ###
