class AccountNotExistsError(Exception): ...


class AccountAlreadyExistsError(Exception): ...


class AccountInactiveError(Exception): ...


class AccountAlreadyVerifiedError(Exception): ...


class InvalidVerificationTokenError(Exception): ...


class InvalidResetTokenError(Exception): ...
