from enum import StrEnum


class Emoji(StrEnum):
    mag = "🔍"
    """🔍"""
    memo = "📝"
    """📝"""
    wrench = "🔧"
    """🔧"""
    white_check_mark = "✅"
    """✅"""
    ballot_box_with_check = "☑️"
    """☑️"""
    camera = "📷"
    """📷"""
    camera_with_flash = "📸"
    """📸"""
    movie_camera = "🎥"
    """🎥"""
    video_camera = "📹"
    """📹"""
    musical_note = "🎵"
    """🎵"""
    next_track = "⏭️"
    """⏭️"""
    bust_in_silhouette = "👤"
    """👤"""
    busts_in_silhouette = "👥"
    """👥"""
    heavy_plus_sign = "➕"
    """➕"""
    x = "❌"
    """❌"""
    round_pushpin = "📍"
    """📍"""
    o2 = "🅾️"
    """🅾️"""
    birthday = "🎂"
    """🎂"""
    label = "🏷"
    """🏷"""
    hash = "#️⃣"
    """#️⃣"""
    restroom = "🚻"
    """🚻"""
    cityscape = "🏙️"
    """🏙️"""
    globe_with_meridians = "🌐"
    """🌐"""
    gb = "🇬🇧"
    """🇬🇧"""
    ru = "🇷🇺"
    """🇷🇺"""
    gear = "⚙️"
    """⚙️"""
    arrow_backward = "◀️"
    """◀️"""
    building_construction = "🏗"
    """🏗"""
    construction = "🚧"
    """🚧"""
    eyes = "👀"
    """👀"""
    information_source = "ℹ️"
    """ℹ️"""
    pencil2 = "✏️"
    """✏️"""
    frame_with_picture = "🖼"
    """🖼"""
    no_entry_sign = "🚫"
    """🚫"""
    infinity = "♾️"
    """♾️"""
    warning = "⚠️"
    """⚠️"""
    no_entry = "⛔️"
    """⛔️"""
    space_invader = "👾"
    """👾"""
    stop_button = "⏹️"
    """⏹️"""
    double_vertical_bar = "⏸️"
    """⏸️"""
    arrow_forward = "▶️"
    """▶️"""
    couple = "👫"
    """👫"""
    hourglass = "⌛️"
    """⌛️"""
    hourglass_flowing_sand = "⏳"
    """⏳"""
    envelope = "✉︎"
    """✉︎"""
    black_heart = "🖤"
    """🖤"""
    two_hearts = "💕"
    """💕"""
    triangular_flag_on_post = "🚩"
    """🚩"""
    star = "⭐️"
    """⭐️"""
    bell = "🔔"
    """🔔"""



    @classmethod
    def get_lang_emoji(cls, key: str):
        return {"en": cls.gb, "ru": cls.ru}.get(key, "")
